# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 612c8c6d0c4d4d2cf49de487f10ec9f2cbf635a2aae982e6a120307b2927f0452d2b727be08606bd584179173b1d81484def7951c2df86d1b9caf5de4477dfe6

test:
  secret_key_base: 4b89e60907f6548ea5508b129039044abc897c92af16a577cbd1f4bdebb463b1b44e54edca21a145a83bcc6e0aaaf849a37e7fb9ed35baef4a5d2b9fd65d713a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
